# Generated by Django 6.0 on 2026-01-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_tag_alter_post_options_post_excerpt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="covers/%Y/%m/",
                verbose_name="封面图片",
            ),
        ),
    ]
